import Image from 'next/image'
import React from 'react'
import CarAddCard from '../Cards/CarAddCard'

const RightBoard = () => {
    let Cars_Adds=[
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-09-23/a00aa29666d646e0888d0cc1320eb2d3/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://spn-mda.spinny.com/img/vFzh1msBTAq%2BPtLAZ6_Oug/file.JPG?q=85&w=360","https://spn-mda.spinny.com/img/rje3MYvbRCecCukqfAahLw/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://spn-mda.spinny.com/img/ij7K77RiQu%2BZpXLaQNIIfA/file.JPG?q=85&w=360","https://spn-mda.spinny.com/img/Dwwic8snTNucKWnS9p2U_A/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-09/2dd1ec895cf74b088cff139f5cdadb29/file.JPG?q=85&w=360",""],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/f516cf7f96dd4aa5a7f5dcb295a8e256/file.JPG?q=85&w=360",""],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/e151705495c24d70b6ab436505c4998f/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/e767998efb1d4c0db85723cfb8c5452a/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/e7eae055232f4dbbaa246d7d6b8ec6d3/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/df166b7bbcbc409c9038a4af0dacfd2f/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/dd171deea2b04baab28d0b7b571750d0/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/dd3dfcbfab884727bc28ee3a3caf0034/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/dccc344981ad4a7bb733f9504daf0c5f/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/c886f329a9444a61928fb0739949bef7/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/c666fc6350414da48615e72a135ad7e2/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/be62f245b8214526b95ac4d380d7ce5b/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/b09363a119fa4218817423742f4eeaad/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/b3c78132d41a4f0fbc4e7f60c867ffaa/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/a0c733d09fc94729953448e55475af53/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/3866505ef0fb4ef782ad157ca1efc27f/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/2914782a1c8e4575bdf15f15e1df38bb/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/2147918b7e5e4da3916bf0c2119d41e6/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/410902d1ad8b45eba059cd8fa70164f6/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/348401c1eb4645d98d23d1c39ed845cc/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/93773b91d2c54023b5bbd1cdbd553ba7/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/047108b3dcf5413cb7eb38bd4c21b3d6/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/30055ecd84dc41e1b81b08e05075bced/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/9517f21c0a9b456e9d48840600aa2f00/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/8445bae62d7e4a4c93e8b2a33d7501d4/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/7815b49ae61649639e063ab9fa85dd9d/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/4421c44304584006b330bf00d9238a3d/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/1995b2ee519444d69b93465c8631fd92/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/948aa5e08753408d8bf7f281e4f72bab/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/668bb0e56a1e4dfbabea329b527a0fe7/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/599a5e86e0f34a2cb4cc22703802f32d/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/482a7332c03a453a90378ef2ff07cd9e/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/304f01f65b0d47ecaeea5499d261b8be/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/93e036c8f3284171931afc53c1f029fd/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/91f7e4c3c75743768807e22842f85aa6/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/74d264c7f0c8477983cd6527e239f764/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/68cb4d3417fe4758815a6a387b897d77/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/060ebcaf4bd5453ba2d8de08acdbecb9/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/56f3d669104d418f871f419a4b564b7c/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/33dcbe291f574099961b78024cadf2ac/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/26e34d6374354881bdb101d7d3ae8367/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/22e92ca696a24dfe89f93e7d9701c9d4/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/9bed7ef351bf49ee9a356a12873e5946/file.JPG?q=85&w=360","https://mda.spinny.com/sp-file-system/public/2024-10-08/9a3a0cdcbd404c44b7958aa25666ee1c/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/8cb5b60c38964ab79dcc4a7068406329/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },
        {
            Images:["https://mda.spinny.com/sp-file-system/public/2024-10-08/1c05853521d64471a74d2e2273d5194c/file.JPG?q=85&w=360"],
            Y_O_Manufacture:"2022",
            Brand_Name:"Skoda",
            Model:"Slavia Style 1.0L TSI MT",
            KM_Driven:"39K",
            Fule_Type:"Petrol",
            Transmission:"Manual",
            Discounted_Price:"12.31",
            Price:"12.22",
            EMI:"22,408",
            T_D_Location:"Gaur City, Noida",
            Body_Type:"Sedan",
            Title:"",
            Car_Name:"",
            Color:"blue",
            Features:["Sunroof","Keless Entry","Airbags"],
        },      
        
    ]
  return (
    <div className="w-[70%] py-2 pl-5">
              <div className="Parms-Links flex flex-wrap gap-4 items-center mb-5" >
                <span className="text-xs font-bold">Home</span>
                <span className="text-xs font-bold -rotate-90"><svg xmlns="http://www.w3.org/2000/svg" stroke="#2e054e" width="7" height="7" viewBox="0 0 14 8" className=""><path fill="none" fillRule="evenodd" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M386 48L392 54 398 48" transform="translate(-385 -47)"></path></svg></span>
                <span className="text-xs  text-[#2E054E] uppercase">Used cars in delhi NCR</span>
              </div>
              <div className="slider-Images w-full flex items-center mb-5">
                <div className="lg:w-1/2 w-full h-40 pr-5">
                    <img layout="responsive"  className="object-cove w-full h-full" src="https://spn-sta.spinny.com/spinny-web/static-images/assets/images/components/SpinnyMarketingBanner/assets/desktop_fos_dusshera_1.jpg?q=85"/>
                </div>
                <div className="lg:w-1/2 w-full h-40 pr-5">
                    <img layout="responsive"  className="object-cove w-full h-full" src="https://spn-sta.spinny.com/spinny-web/static-images/assets/images/pages/Listing/components/ListingFestivalBanner/assets/assuredPlusBanner.jpg?q=85&w=500"/>
                </div>
              </div>
              <div className="Cars-Number-and-Sort-by flex flex-wrap justify-between items-center">
                    <div className="Cars-Number ">
                        <span className="text-2xl font-bold">1560</span>
                        <span className="text-base ml-1">Used Cars in Delhi NCR</span>
                    </div>
                    <select className="Sort-by border bg-transparent font-semibold outline-none border-gray-400 rounded-md py-4 px-4">
                        <option>Sotr by: Relevance</option>
                        <option>Price-Low to high</option>
                        <option>Price-high to Low</option>
                        <option>KM Driven-Low to High</option>
                        <option>Year-New to Old</option>
                        <option>Newest First</option>
                        <option>Discount- High to Low</option>
                    </select>
              </div>
              <div className="Cars-Cards mt-5 flex flex-wrap items-center ">
                {
                    Cars_Adds?.map((Car_Ad,indx)=>(
                        <CarAddCard key={indx} Car_Ad={Car_Ad}/>
                    ))
                }
              </div>
    </div>
  )
}

export default RightBoard